### PR TITLE
Setup CI and lints (using GitHub Actions)

### PR DESCRIPTION
**Pull request by luizirber**
These are based on the niffler GH Actions, need to adapt some extra things (like Minimum Supported Rust Version)

### CODE REVIEW

**Comment by luizirber** [comment]
Example run in my fork: https://github.com/luizirber/nuc2bit/actions/runs/225898057
(it won't trigger here because I'm not a member)

**Comment by luizirber** [comment]
Some fun things:
- `cargo fmt` is failing, so I commented it out.
- `cargo clippy` has a bunch of recommended fixes, commented it out too.
- Running tests on windows [generates a Heap corruption error](https://github.com/luizirber/nuc2bit/pull/1/checks?check_run_id=1033491496#step:4:154) :fearful:, disabled for now.

All the commented out checks are in commit https://github.com/natir/nuc2bit/pull/6/commits/f5ce5deba63706293a7e2bd0f1156ea372166d71, so it can be reverted when they pass.

On top of the niffler CI checks I also added a benchmark job based on https://github.com/rhysd/github-action-benchmark/tree/e47c97d3e7d45119a6cdc04c2da04593ab96dba3/examples/criterion-rs, which will put a comment if there is a performance regression in the benchmarks (just found out about it, gonna add to my projects too =])

Ready for review @natir @Daniel-Liu-c0deb0t

**Review by natir — APPROVED** [review]
If it's ok for @Daniel-Liu-c0deb0t you can merge. 

(I reduce the number of tested value length benchmark near in future)

**Comment by luizirber** [comment]
(It's taking over an hour to run benchmarks in GitHub Actions =P)

**Comment by Daniel-Liu-c0deb0t** [comment]
Wow that is quite a comprehensive workflow. Looks good!

If I recall correctly, Github actions isn't the most reliable way for getting accurate benchmark numbers, since their server speed varies quite a bit. However, it is still good to run the benchmarks so we know everything works. Like what @natir said, if the benchmarks take too long, then we can always reduce the number of iterations.

**Pull request merged**
